# Generated by Django 5.1 on 2024-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testssl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='value_sslv2',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='value_sslv3',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='value_tls1',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='value_tls11',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='value_tls12',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='value_tls13',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
