# Generated by Django 5.1 on 2025-04-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testssl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='cert',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='cert_sig_alg',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='ecdhe_curves',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='kems',
            field=models.CharField(default='not offered', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls10_ciphers',
            field=models.CharField(default='not offered', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls11_ciphers',
            field=models.CharField(default='not offered', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls12_ciphers',
            field=models.CharField(default='not offered', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls12_sig_alg',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls13_ciphers',
            field=models.CharField(default='not offered', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='tls13_sig_alg',
            field=models.CharField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_sslv2',
            field=models.CharField(default='not offered', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_sslv3',
            field=models.CharField(default='not offered', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_tls1',
            field=models.CharField(default='not offered', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_tls11',
            field=models.CharField(default='not offered', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_tls12',
            field=models.CharField(default='not offered', max_length=100),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='value_tls13',
            field=models.CharField(default='not offered', max_length=100),
        ),
    ]
