# Generated by Django 5.1 on 2024-12-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testssl_app', '0002_urlitem_value_sslv2_urlitem_value_sslv3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
