# Generated by Django 5.1 on 2025-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testssl_app', '0004_policy_policyrule_rule_subrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlitem',
            name='cert',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='cert_sig_alg',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='ecdhe_curves',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='kems',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls10_ciphers',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls11_ciphers',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls12_ciphers',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls12_sig_alg',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls13_ciphers',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
        migrations.AddField(
            model_name='urlitem',
            name='tls13_sig_alg',
            field=models.CharField(default='Unknown', max_length=10000),
        ),
    ]
