# Generated by Django 5.1 on 2024-08-21 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
